### ISSUE TITLE
Trivy scan detects multiple misconfigurations

### ISSUE THREAD

**Issue by aayani** [mscdex/cpu-features#21]
<img width="2091" alt="Screenshot 2024-03-05 at 15 57 53" src="https://github.com/mscdex/cpu-features/assets/32307105/5360efd9-3530-48ea-a7ee-57214e9661c0">

**Comment by mscdex** [comment]
As you can see by the paths, those are all inside the cpu_features upstream project. You should submit an issue to that project instead.

**Comment by hpeters83** [comment]
Hi @mscdex ,

Thanks for your work on this package. However, we are facing the same scanning issues. I think the issue here is that these files should not be pushed to NPM and can be ignored:

https://github.com/google/cpu_features/issues/349

So you should add an .npmignore when you publish to npm.

**Comment by mscdex** [comment]
@hpeters83 The way I see it it's either a cpu_features issue or a Trivy issue. I'm not really interested in meddling with a dependency's files.
