### ISSUE TITLE
npm install fails

### ISSUE THREAD

**Issue by somanuell** [mscdex/cpu-features#4]
Due to you closing https://github.com/mscdex/cpu-features/issues/3 without releasing a new version on npmjs.com, `npm install cpu-features` still fails on Windows

**Comment by somanuell** [comment]
I don't understand. You have approx. 400k downloads a week on npmjs.com, none of them can successfully install on windows... please explain to me why you don't bump the version. What is the problem?

**Comment by mscdex** [comment]
I closed #3 because the fix was committed to the repository -- thus the problem was solved and the issue did not need to remain open.

Like the rest of my open source projects, I work on `cpu-features` in my *spare/free time*, like many other developers do for their own open source projects. Sometimes that means releases may not happen as often as some would like. Sometimes that means issues/PRs may not get addressed in a timely manner. That's just how it goes when software projects don't pay the bills and are a lower priority relative to other things in life.

Additionally, keep in mind that I may not be ready to make a release yet. In fact, I have other changes I'm still working on that I would like to finish first.

Lastly, since [it appears](https://stackoverflow.com/questions/69372995/how-to-npm-i-ssh2-without-errors-on-windows) that the reason #3 was opened in the first place was because of `ssh2`'s *optional* dependency on `cpu-features`, this is even less of an issue because of the *optional* aspect -- it is not required to use `ssh2`. If you want npm to ignore optional dependencies completely or want npm to hide logged output for failed *optional* dependency installations, then that is an npm problem, not that of `ssh2` or `cpu-features`. Also as far as npm goes, both of those *npm-specific issues* should already have solutions.

**Comment by somanuell** [comment]
I fully understand the "spare/free" time issue. However, currently, "cpu_features" fails to install, on Windows, with ugly messages about some unresolved externals.

Your code, your choice, so, OK, the issue "npm install fails" is now "closed".

**Comment by avin-kavish** [comment]
I use `patch-package` locally or fork and re-release the package under my namespace to get fixes on my own schedule.
